// <auto-generated />
using EmissorMdfe.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmissorMdfe.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218123654_AdicionaControleNumeracao")]
    partial class AdicionaControleNumeracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("EmissorMdfe.Core.Models.Condutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Condutores");
                });

            modelBuilder.Entity("EmissorMdfe.Core.Models.ConfiguracaoApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ambiente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BairroEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoCertificado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CepEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CidadeEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CnpjEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CodigoIbgeCidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IeEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogradouroEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocialEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaCertificado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoEmitente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UfEmitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UltimoNumeroMdfe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("EmissorMdfe.Core.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadeKG")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rntrc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaraKG")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoCarroceria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoRodado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UfLicenciamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
